sudo: required

env:
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""

services:
  - docker

 
before_install:
   # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  # Customize container
  - 'sudo docker build --rm=true --file=docker/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible docker'

script:
  - container_id=$(mktemp)
  
  - mount_point=/root/scrapy-cluster

  - docker_shell="sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm /bin/bash -c"

  # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD}":${mount_point}:rw ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'
    
  # Run offline tests
  - '${docker_shell} "virtualenv ~/sc; source ~/sc/bin/activate; pip install -r ~/scrapy-cluster/requirements.txt; cd ~/scrapy-cluster/; find . -name "*.pyc" -type f -delete; cd utils; python setup.py install; cd ../; ./run_offline_tests.sh;"'
  
  # Ansible syntax check.
  - '${docker_shell} "ansible-playbook -i ~/scrapy-cluster/ansible/travis.inventory ~/scrapy-cluster/ansible/scrapy-cluster.yml --syntax-check"'

  # Ansible install playbook.
  - '${docker_shell} "ansible-playbook -i ~/scrapy-cluster/ansible/travis.inventory ~/scrapy-cluster/ansible/scrapy-cluster.yml --connection=local --become"'  
  
  # Run offline, online tests and coverage
  - '${docker_shell} "source ~/sc/bin/activate; cd ~/scrapy-cluster/; ./run_online_tests.sh; pip install coveralls; coveralls;"'
  
  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  slack:
    rooms:
      secure: nPY+SvgkOrpvU76i55bDtXPbclq7WzY2DCwOCbYNzpMMTNnlqV9uhwUc31gHdl+xO8aXf52JwuOqTZnJTi9PGuomp7qf4N4z/dz3tKdjj3ppgeDx8hcmAikiM/qoOUadA9zNvP+wHfJSK7l6LnbAZgdOAXZb77Fk5rIuRr695vg=
    on_success: always
    on_failure: always
    on_start: always