---
- name: create zookeeper install directory
  file:
    path={{ item }}
    state=directory
    mode=0744
  with_items:
    - "{{ zookeeper_install_dir }}"
  tags: zookeeper

- name: check for existing install
  stat: path={{ zookeeper_install_dir }}/zookeeper-{{ zookeeper_version }}
  register: zookeeper
  tags: zookeeper

- name: download zookeeper
  get_url:
    url="{{ zookeeper_source }}/zookeeper-{{ zookeeper_version }}.tar.gz"
    dest=/tmp/zookeeper-{{ zookeeper_version }}.tgz
    mode=0644
    validate_certs=no
  when: zookeeper.stat.isdir is not defined
  tags: zookeeper

- name: extract zookeeper
  unarchive:
    src=/tmp/zookeeper-{{ zookeeper_version }}.tgz
    dest={{ zookeeper_install_dir }}
    copy=no
  when: zookeeper.stat.isdir is not defined
  tags: zookeeper

- name: delete temporary zookeeper file
  file:
    path=/tmp/zookeeper-{{ zookeeper_version }}.tgz
    state=absent
  ignore_errors: yes
  tags: zookeeper

- name: create zookeeper symlink
  file:
    path={{ zookeeper_install_dir }}/default
    state=link
    src={{ zookeeper_install_dir }}/zookeeper-{{ zookeeper_version }}
  tags: zookeeper

- name: create zookeeper directories
  file:
    path={{ item }}
    state=directory
    mode=0744
  with_items:
    - "{{ zookeeper_conf_dir }}"
    - "{{ zookeeper_log_dir }}"
    - "{{ zookeeper_data_dir }}"
  tags: zookeeper

- name: copy supervisord config
  template:
    src=zookeeper-supervisord.conf.j2
    dest={{ supervisord_programs_dir }}/zookeeper-supervisord.conf
    mode=0644
  notify:
    - reread supervisord
  tags: zookeeper

- name: setup zoo.cfg
  template:
    dest={{ zookeeper_conf_dir }}/zoo.cfg
    src=zoo.cfg.j2
  notify:
    - restart zookeeper
    - wait for zookeeper port
  tags: zookeeper

# - name: check for existing data directory
#   stat: path={{ zookeeper_data_dir }}
#   register: data_exists
#   tags: zookeeper

# - name: initialize data directory
#   shell: "{{service zookeeper-server init}}"
#   when: data_exists.stat.isdir is not defined
#   tags: zookeeper

- name: setup myid file for zookeeper
  template:
    dest={{zookeeper_data_dir}}/myid
    src=myid.j2
  notify:
    - restart zookeeper
    - wait for zookeeper port
  tags: zookeeper

- name: set up aliases
  lineinfile:
    dest: "~/.bashrc"
    line: "alias zkcli='{{ zookeeper_base_dir }}/bin/zkCli.sh'"
  tags: alias
