---
- name: Install apt-get packages
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    state: latest
    cache_valid_time: 600
  with_items:
    - python-lxml
    - build-essential
    - libssl-dev
    - libffi-dev
    - python-dev
    - libxml2-dev
    - libxslt1-dev
  tags: common
  when: ansible_os_family == "Debian"

- name: Install EPEL repo.
  yum:
    name: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  tags: common
  when: ansible_os_family == "RedHat"

- name: Import EPEL GPG key.
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present
  tags: common
  when: ansible_os_family == "RedHat"

- name: Install 'Development tools' group of packages
  tags: common
  yum: name='@Development tools' state=installed
  when: ansible_os_family == "RedHat"

- name: Install yum packages
  yum:
    name={{ item }}
    state=present
  with_items:
    - python-lxml
    - openssl-devel
    - libffi
    - libffi-devel
    - python-devel
    - libxml2-devel
    - libxslt-devel
  tags: common
  when: ansible_os_family == "RedHat"