---

zookeeper_version: 3.4.6

zookeeper_install_dir: /opt/zookeeper
zookeeper_base_dir: "{{ zookeeper_install_dir }}/default"
zookeeper_conf_dir: "{{ zookeeper_base_dir }}/conf"
zookeeper_data_dir: "{{ zookeeper_base_dir }}/data"
zookeeper_log_dir: "{{ zookeeper_base_dir }}/logs"


zookeeper_client_port: 2181
zookeeper_conn_port: 2888
zookeeper_lead_port: 3888
zookeeper_tick_time: 2000
zookeeper_init_limit: 10
zookeeper_sync_limit: 5
zookeeper_maxClientCnxns: 60
zookeeper_auto_purge_interval: 24
zookeeper_auto_purge_snap_retain_count: 5

zookeeper_source: "http://archive.apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}"
